/**
 * Terms of Use Page
 */

import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import { FileText } from 'lucide-react';
import { Logo, Button, Footer } from '../components';

const sections = [
  {
    title: '1. Acceptance of Terms',
    content: `By accessing or using MoodMirror, you agree to be bound by these Terms of Use. If you do not agree with any part of these terms, you must not use the application.`,
  },
  {
    title: '2. Research Tool — Not a Medical Device',
    content: `MoodMirror is a research prototype developed as an academic project. It is NOT a medical device, clinical diagnostic tool, or substitute for professional mental health care. Results generated by MoodMirror should not be used to make clinical, medical, or psychological decisions. Always consult a qualified mental health professional for any health-related concerns.`,
  },
  {
    title: '3. Eligibility',
    content: `You must be at least 18 years of age and have a valid Reddit account to use MoodMirror. By using this service, you confirm that you meet these requirements.`,
  },
  {
    title: '4. Reddit Account Access',
    content: `You authorise MoodMirror to access your public Reddit posts and comments via Reddit's OAuth system, solely for the purpose of generating your analysis. You can revoke this access at any time through Reddit's application settings.`,
  },
  {
    title: '5. No Liability for Results',
    content: `MoodMirror makes no warranties — express or implied — about the accuracy, completeness, or suitability of its risk assessments. The developers of MoodMirror shall not be liable for any decisions made based on results provided by the application, or for any direct, indirect, or consequential damages arising from its use.`,
  },
  {
    title: '6. Crisis Situations',
    content: `If you are experiencing a mental health crisis, MoodMirror is NOT an appropriate tool to use. Please contact emergency services, the 988 Suicide & Crisis Lifeline, or your nearest mental health facility immediately.`,
  },
  {
    title: '7. Prohibited Use',
    content: `You agree not to use MoodMirror to: (a) analyse other users' accounts without their consent; (b) attempt to reverse-engineer or exploit the system; (c) use the tool for any commercial purpose; or (d) misrepresent results as clinical diagnoses.`,
  },
  {
    title: '8. Intellectual Property',
    content: `All content, design, and code within MoodMirror are the intellectual property of the developers unless otherwise stated. You may not reproduce or redistribute any part of the application without express permission.`,
  },
  {
    title: '9. Modifications',
    content: `These Terms of Use may be updated at any time. Continued use of MoodMirror after changes are posted constitutes your acceptance of the new terms.`,
  },
  {
    title: '10. Governing Law',
    content: `These Terms are governed by the applicable laws of the jurisdiction in which the application was developed. Any disputes shall be resolved under those laws.`,
  },
];

export function TermsPage() {
  return (
    <div className="bg-animated flex flex-col min-h-screen">
      <header className="fixed top-0 left-0 right-0 z-50 bg-slate-900/50 backdrop-blur-lg border-b border-white/5">
        <div className="container-narrow flex justify-between items-center h-16">
          <Logo size="sm" />
          <Link to="/">
            <Button variant="secondary" size="sm">Back to Home</Button>
          </Link>
        </div>
      </header>

      <main className="flex-1 pt-24 pb-16">
        <div className="container-narrow max-w-3xl">
          <motion.div className="text-center py-10" initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}>
            <FileText size={48} className="text-purple-400 mx-auto mb-4" />
            <h1 className="text-3xl font-bold text-white mb-2">Terms of Use</h1>
            <p className="text-slate-400 text-sm">Effective date: January 2026</p>
          </motion.div>

          <div className="p-5 mb-8 rounded-2xl bg-amber-500/10 border border-amber-500/30">
            <p className="text-amber-300 text-sm font-medium">
              ⚠️ MoodMirror is a research prototype and NOT a clinical tool.
              Results must not be used as medical advice.
            </p>
          </div>

          <div className="space-y-8">
            {sections.map((section, i) => (
              <motion.div
                key={section.title}
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.05 * i }}
              >
                <h2 className="text-lg font-semibold text-white mb-2">{section.title}</h2>
                <p className="text-sm text-slate-400 leading-relaxed">{section.content}</p>
              </motion.div>
            ))}
          </div>

          <div className="mt-12 p-5 glass-card text-center">
            <p className="text-slate-400 text-sm">
              Questions about these terms?{' '}
              <Link to="/contact" className="text-purple-400 hover:text-purple-300 transition-colors">Contact us</Link>
            </p>
          </div>
        </div>
      </main>

      <Footer />
    </div>
  );
}
